package com.example.googlemapspractice;

import java.util.ArrayList;
import java.util.List;

public class UniversityData {
    public static void main(String[] args) {
        List<University> universities = new ArrayList<>();

        universities.add(new University("Alabama", "Alabama A & M University", 10024, 18634));
        universities.add(new University("Alabama", "Alabama State University", 11068, 19396));
        universities.add(new University("Alabama", "Amridge University", 9000, 9000));
        universities.add(new University("Alabama", "Athens State University", 7230, 14460));
        universities.add(new University("Alabama", "Auburn University", 12176, 32960));
        universities.add(new University("Alabama", "Auburn University at Montgomery", 9100, 19348));
        universities.add(new University("Alabama", "Birmingham-Southern College", 21250, 21250));
        universities.add(new University("Alabama", "Columbia Southern University", 6015, 6015));
        universities.add(new University("Alabama", "Faulkner University", 23920, 23920));
        universities.add(new University("Alabama", "Heritage Christian University", 11632, 11632));
        universities.add(new University("Alabama", "Herzing University-Birmingham", 12750, 12750));
        universities.add(new University("Alabama", "Huntingdon College", 28350, 28350));
        universities.add(new University("Alabama", "Huntsville Bible College", 4730, 4730));
        universities.add(new University("Alabama", "Jacksonville State University", 11952, 21912));
        universities.add(new University("Alabama", "Miles College", 12714, 12714));
        universities.add(new University("Alabama", "Oakwood University", 20040, 20040));
        universities.add(new University("Alabama", "Samford University", 36725, 36725));
        universities.add(new University("Alabama", "Selma University", 4800, 4800));
        universities.add(new University("Alabama", "South University-Montgomery", 17014, 17014));
        universities.add(new University("Alabama", "Spring Hill College", 21732, 21732));
        universities.add(new University("Alabama", "Stillman College", 11392, 11392));
        universities.add(new University("Alabama", "Strayer University-Alabama", 13515, 13515));
        universities.add(new University("Alabama", "Talladega College", 13866, 13866));
        universities.add(new University("Alabama", "The University of Alabama", 11940, 32300));
        universities.add(new University("Alabama", "Troy University", 9312, 18624));
        universities.add(new University("Alabama", "Tuskegee University", 22614, 22614));
        universities.add(new University("Alabama", "United States Sports Academy", 16418, 16418));
        universities.add(new University("Alabama", "University of Alabama at Birmingham", 8832, 21216));
        universities.add(new University("Alabama", "University of Alabama in Huntsville", 11878, 24770));
        universities.add(new University("Alabama", "University of Mobile", 25880, 25880));
        universities.add(new University("Alabama", "University of Montevallo", 13710, 26730));
        universities.add(new University("Alabama", "University of North Alabama", 11220, 21420));
        universities.add(new University("Alabama", "University of South Alabama", 9116, 17732));
        universities.add(new University("Alabama", "University of West Alabama", 10990, 20090));
        universities.add(new University("Alaska", "Alaska Bible College", 10900, 10900));
        universities.add(new University("Alaska", "Alaska Pacific University", 20760, 20760));
        universities.add(new University("Alaska", "Ilisagvik College", 5260, 5260));
        universities.add(new University("Alaska", "University of Alaska Anchorage", 7508, 21635));
        universities.add(new University("Alaska", "University of Alaska Fairbanks", 7896, 22032));
        universities.add(new University("Alaska", "University of Alaska Southeast", 6960, 21096));
        universities.add(new University("Arizona", "American InterContinental University", 12422, 12422));
        universities.add(new University("Arizona", "Arizona Christian University", 31650, 31650));
        universities.add(new University("Arizona", "Arizona College of Nursing - Phoenix", 24000, 24000));
        universities.add(new University("Arizona", "Arizona College of Nursing - Tempe", 24000, 24000));
        universities.add(new University("Arizona", "Arizona College of Nursing - Tucson", 22826, 22826));
        universities.add(new University("Arizona", "Arizona State University Campus Immersion", 11618, 30592));
        universities.add(new University("Arizona", "Arizona State University Digital Immersion", 10978, 13248));
        universities.add(new University("Arizona", "Aspen University", 5355, 5355));
        universities.add(new University("Arizona", "Brookline College - Phoenix", 89404, 89404));
        universities.add(new University("Arizona", "Brookline College - Tempe", 30150, 30150));
        universities.add(new University("Arizona", "Brookline College - Tucson", 31150, 31150));
        universities.add(new University("Arizona", "Bryan University", 12184, 12184));
        universities.add(new University("Arizona", "Chamberlain University - Arizona", 20142, 20142));
        universities.add(new University("Arizona", "DeVry University - Arizona", 17488, 17488));
        universities.add(new University("Arizona", "Dine College", 1410, 1410));
        universities.add(new University("Arizona", "Embry-Riddle Aeronautical University - Prescott", 40464, 40464));
        universities.add(new University("Arizona", "Grand Canyon University", 17800, 17800));
        universities.add(new University("Arizona", "Indian Bible College", 7420, 7420));
        universities.add(new University("Arizona", "International Baptist College and Seminary", 13200, 13200));
        universities.add(new University("Arizona", "National Paralegal College", 7995, 7995));
        universities.add(new University("Arizona", "Northern Arizona University", 12274, 27536));
        universities.add(new University("Arizona", "Ottawa University - Phoenix", 12641, 12641));
        universities.add(new University("Arizona", "Ottawa University - Surprise", 33000, 33000));
        universities.add(new University("Arizona", "Pima Medical Institute - Tucson", 24475, 24475));
        universities.add(new University("Arizona", "Prescott College", 35450, 35450));
        universities.add(new University("Arizona", "Sessions College for Professional Design", 12440, 12440));
        universities.add(new University("Arizona", "University of Advancing Technology", 18794, 18794));
        universities.add(new University("Arizona", "University of Arizona", 13275, 39577));
        universities.add(new University("Arizona", "University of Phoenix - Arizona", 9552, 9552));
        universities.add(new University("Arkansas", "Arkansas Baptist College", 8760, 8760));
        universities.add(new University("Arkansas", "Arkansas State University", 7456, 13312));
        universities.add(new University("Arkansas", "Arkansas Tech University", 8071, 13891));
        universities.add(new University("Arkansas", "Central Baptist College", 17700, 17700));
        universities.add(new University("Arkansas", "Champion Christian College", 7755, 7755));
        universities.add(new University("Arkansas", "Crowley's Ridge College", 15000, 15000));
        universities.add(new University("Arkansas", "Ecclesia College", 16850, 16850));
        universities.add(new University("Arkansas", "Harding University", 23148, 23148));
        universities.add(new University("Arkansas", "Henderson State University", 7560, 9768));
        universities.add(new University("Arkansas", "Hendrix College", 35100, 35100));
        universities.add(new University("Arkansas", "Jackson Theological Seminary", 6000, 6000));
        universities.add(new University("Arkansas", "John Brown University", 29720, 29720));
        universities.add(new University("Arkansas", "Lyon College", 31000, 31000));
        universities.add(new University("Arkansas", "Ouachita Baptist University", 31180, 31180));
        universities.add(new University("Arkansas", "Philander Smith College", 13014, 13014));
        universities.add(new University("Arkansas", "Southern Arkansas University Main Campus", 9680, 15110));
        universities.add(new University("Arkansas", "Strayer University - Arkansas", 13515, 13515));
        universities.add(new University("Arkansas", "University of Arkansas", 9656, 27410));
        universities.add(new University("Arkansas", "University of Arkansas at Little Rock", 8366, 18957));
        universities.add(new University("Arkansas", "University of Arkansas at Monticello", 8431, 14281));
        universities.add(new University("Arkansas", "University of Arkansas at Pine Bluff", 8668, 15838));
        universities.add(new University("Arkansas", "University of Arkansas for Medical Sciences", 7068, 14586));
        universities.add(new University("Arkansas", "University of Arkansas Grantham", 8280, 8280));
        universities.add(new University("Arkansas", "University of Arkansas - Fort Smith", 6168, 13440));
        universities.add(new University("Arkansas", "University of Central Arkansas", 9778, 16728));
        universities.add(new University("Arkansas", "University of the Ozarks", 25950, 25950));
        universities.add(new University("Arkansas", "Williams Baptist University", 19450, 19450));
    }
}

