package com.example.googlemapspractice;

import java.util.ArrayList;
import java.util.List;

public class UniversityData {
    public static void main(String[] args) {
        List<University> universities = new ArrayList<>();

        universities.add(new University("Alabama", "Alabama A & M University", 10024, 18634));
        universities.add(new University("Alabama", "Alabama State University", 11068, 19396));
        universities.add(new University("Alabama", "Amridge University", 9000, 9000));
        universities.add(new University("Alabama", "Athens State University", 7230, 14460));
        universities.add(new University("Alabama", "Auburn University", 12176, 32960));
        universities.add(new University("Alabama", "Auburn University at Montgomery", 9100, 19348));
        universities.add(new University("Alabama", "Birmingham-Southern College", 21250, 21250));
        universities.add(new University("Alabama", "Columbia Southern University", 6015, 6015));
        universities.add(new University("Alabama", "Faulkner University", 23920, 23920));
        universities.add(new University("Alabama", "Heritage Christian University", 11632, 11632));
        universities.add(new University("Alabama", "Herzing University-Birmingham", 12750, 12750));
        universities.add(new University("Alabama", "Huntingdon College", 28350, 28350));
        universities.add(new University("Alabama", "Huntsville Bible College", 4730, 4730));
        universities.add(new University("Alabama", "Jacksonville State University", 11952, 21912));
        universities.add(new University("Alabama", "Miles College", 12714, 12714));
        universities.add(new University("Alabama", "Oakwood University", 20040, 20040));
        universities.add(new University("Alabama", "Samford University", 36725, 36725));
        universities.add(new University("Alabama", "Selma University", 4800, 4800));
        universities.add(new University("Alabama", "South University-Montgomery", 17014, 17014));
        universities.add(new University("Alabama", "Spring Hill College", 21732, 21732));
        universities.add(new University("Alabama", "Stillman College", 11392, 11392));
        universities.add(new University("Alabama", "Strayer University-Alabama", 13515, 13515));
        universities.add(new University("Alabama", "Talladega College", 13866, 13866));
        universities.add(new University("Alabama", "The University of Alabama", 11940, 32300));
        universities.add(new University("Alabama", "Troy University", 9312, 18624));
        universities.add(new University("Alabama", "Tuskegee University", 22614, 22614));
        universities.add(new University("Alabama", "United States Sports Academy", 16418, 16418));
        universities.add(new University("Alabama", "University of Alabama at Birmingham", 8832, 21216));
        universities.add(new University("Alabama", "University of Alabama in Huntsville", 11878, 24770));
        universities.add(new University("Alabama", "University of Mobile", 25880, 25880));
        universities.add(new University("Alabama", "University of Montevallo", 13710, 26730));
        universities.add(new University("Alabama", "University of North Alabama", 11220, 21420));
        universities.add(new University("Alabama", "University of South Alabama", 9116, 17732));
        universities.add(new University("Alabama", "University of West Alabama", 10990, 20090));
        universities.add(new University("Alaska", "Alaska Bible College", 10900, 10900));
        universities.add(new University("Alaska", "Alaska Pacific University", 20760, 20760));
        universities.add(new University("Alaska", "Ilisagvik College", 5260, 5260));
        universities.add(new University("Alaska", "University of Alaska Anchorage", 7508, 21635));
        universities.add(new University("Alaska", "University of Alaska Fairbanks", 7896, 22032));
        universities.add(new University("Alaska", "University of Alaska Southeast", 6960, 21096));
        universities.add(new University("Arizona", "American InterContinental University", 12422, 12422));
        universities.add(new University("Arizona", "Arizona Christian University", 31650, 31650));
        universities.add(new University("Arizona", "Arizona College of Nursing - Phoenix", 24000, 24000));
        universities.add(new University("Arizona", "Arizona College of Nursing - Tempe", 24000, 24000));
        universities.add(new University("Arizona", "Arizona College of Nursing - Tucson", 22826, 22826));
        universities.add(new University("Arizona", "Arizona State University Campus Immersion", 11618, 30592));
        universities.add(new University("Arizona", "Arizona State University Digital Immersion", 10978, 13248));
        universities.add(new University("Arizona", "Aspen University", 5355, 5355));
        universities.add(new University("Arizona", "Brookline College - Phoenix", 89404, 89404));
        universities.add(new University("Arizona", "Brookline College - Tempe", 30150, 30150));
        universities.add(new University("Arizona", "Brookline College - Tucson", 31150, 31150));
        universities.add(new University("Arizona", "Bryan University", 12184, 12184));
        universities.add(new University("Arizona", "Chamberlain University - Arizona", 20142, 20142));
        universities.add(new University("Arizona", "DeVry University - Arizona", 17488, 17488));
        universities.add(new University("Arizona", "Dine College", 1410, 1410));
        universities.add(new University("Arizona", "Embry-Riddle Aeronautical University - Prescott", 40464, 40464));
        universities.add(new University("Arizona", "Grand Canyon University", 17800, 17800));
        universities.add(new University("Arizona", "Indian Bible College", 7420, 7420));
        universities.add(new University("Arizona", "International Baptist College and Seminary", 13200, 13200));
        universities.add(new University("Arizona", "National Paralegal College", 7995, 7995));
        universities.add(new University("Arizona", "Northern Arizona University", 12274, 27536));
        universities.add(new University("Arizona", "Ottawa University - Phoenix", 12641, 12641));
        universities.add(new University("Arizona", "Ottawa University - Surprise", 33000, 33000));
        universities.add(new University("Arizona", "Pima Medical Institute - Tucson", 24475, 24475));
        universities.add(new University("Arizona", "Prescott College", 35450, 35450));
        universities.add(new University("Arizona", "Sessions College for Professional Design", 12440, 12440));
        universities.add(new University("Arizona", "University of Advancing Technology", 18794, 18794));
        universities.add(new University("Arizona", "University of Arizona", 13275, 39577));
        universities.add(new University("Arizona", "University of Phoenix - Arizona", 9552, 9552));
        universities.add(new University("Arkansas", "Arkansas Baptist College", 8760, 8760));
        universities.add(new University("Arkansas", "Arkansas State University", 7456, 13312));
        universities.add(new University("Arkansas", "Arkansas Tech University", 8071, 13891));
        universities.add(new University("Arkansas", "Central Baptist College", 17700, 17700));
        universities.add(new University("Arkansas", "Champion Christian College", 7755, 7755));
        universities.add(new University("Arkansas", "Crowley's Ridge College", 15000, 15000));
        universities.add(new University("Arkansas", "Ecclesia College", 16850, 16850));
        universities.add(new University("Arkansas", "Harding University", 23148, 23148));
        universities.add(new University("Arkansas", "Henderson State University", 7560, 9768));
        universities.add(new University("Arkansas", "Hendrix College", 35100, 35100));
        universities.add(new University("Arkansas", "Jackson Theological Seminary", 6000, 6000));
        universities.add(new University("Arkansas", "John Brown University", 29720, 29720));
        universities.add(new University("Arkansas", "Lyon College", 31000, 31000));
        universities.add(new University("Arkansas", "Ouachita Baptist University", 31180, 31180));
        universities.add(new University("Arkansas", "Philander Smith College", 13014, 13014));
        universities.add(new University("Arkansas", "Southern Arkansas University Main Campus", 9680, 15110));
        universities.add(new University("Arkansas", "Strayer University - Arkansas", 13515, 13515));
        universities.add(new University("Arkansas", "University of Arkansas", 9656, 27410));
        universities.add(new University("Arkansas", "University of Arkansas at Little Rock", 8366, 18957));
        universities.add(new University("Arkansas", "University of Arkansas at Monticello", 8431, 14281));
        universities.add(new University("Arkansas", "University of Arkansas at Pine Bluff", 8668, 15838));
        universities.add(new University("Arkansas", "University of Arkansas for Medical Sciences", 7068, 14586));
        universities.add(new University("Arkansas", "University of Arkansas Grantham", 8280, 8280));
        universities.add(new University("Arkansas", "University of Arkansas - Fort Smith", 6168, 13440));
        universities.add(new University("Arkansas", "University of Central Arkansas", 9778, 16728));
        universities.add(new University("Arkansas", "University of the Ozarks", 25950, 25950));
        universities.add(new University("Arkansas", "Williams Baptist University", 19450, 19450));
        universities.add(new University("California", "Abraham Lincoln University", 6480, 6480));
        universities.add(new University("California", "Academy of Art University", 26728, 26728));
        universities.add(new University("California", "Agape College of Business and Science", 7942, 7942));
        universities.add(new University("California", "Alliant International University - San Diego", 13680, 13680));
        universities.add(new University("California", "America Evangelical University", 6200, 6200));
        universities.add(new University("California", "American Jewish University", 9720, 9720));
        universities.add(new University("California", "American Medical Sciences Center", 39097, 39097));
        universities.add(new University("California", "American University of Health Sciences", 24575, 24575));
        universities.add(new University("California", "Angeles College", 30010, 30010));
        universities.add(new University("California", "Antelope Valley Community College District", 1124, 7724));
        universities.add(new University("California", "Antioch University - Los Angeles", 16050, 16050));
        universities.add(new University("California", "Antioch University - Santa Barbara", 17820, 17820));
        universities.add(new University("California", "Arizona College - Ontario", 29146, 29146));
        universities.add(new University("California", "Art Center College of Design", 49942, 49942));
        universities.add(new University("California", "Ashford University", 13160, 13160));
        universities.add(new University("California", "ATI College-Whittier", 34900, 34900));
        universities.add(new University("California", "Azusa Pacific University", 42330, 42330));
        universities.add(new University("California", "Bakersfield College", 1430, 9560));
        universities.add(new University("California", "Bergin University of Canine Studies", 9993, 9993));
        universities.add(new University("California", "Bethesda University", 6560, 6560));
        universities.add(new University("California", "Beverly Hills Design Institute", 23220, 23220));
        universities.add(new University("California", "Biola University", 44382, 44382));
        universities.add(new University("California", "California Aeronautical University", 33037, 33037));
        universities.add(new University("California", "California Baptist University", 38058, 38058));
        universities.add(new University("California", "California Christian College", 10890, 10890));
        universities.add(new University("California", "California College of the Arts", 54706, 54706));
        universities.add(new University("California", "California Institute of Integral Studies", 21116, 21116));
        universities.add(new University("California", "California Institute of Technology", 60864, 60864));
        universities.add(new University("California", "California Institute of the Arts", 55056, 55056));
        universities.add(new University("California", "California Intercontinental University", 9054, 9054));
        universities.add(new University("California", "California Jazz Conservatory", 22800, 22800));
        universities.add(new University("California", "California Lutheran University", 48012, 48012));
        universities.add(new University("California", "California Miramar University", 9994, 9994));
        universities.add(new University("California", "California Northstate University", 52685, 52685));
        universities.add(new University("California", "California Polytechnic State University - San Luis Obispo", 10319, 28229));
        universities.add(new University("California", "California State Polytechnic University - Humboldt", 7864, 19744));
        universities.add(new University("California", "California State Polytechnic University - Pomona", 7439, 19319));
        universities.add(new University("California", "California State University Maritime Academy", 7116, 18996));
        universities.add(new University("California", "California State University - Bakersfield", 7637, 19517));
        universities.add(new University("California", "California State University - Channel Islands", 6817, 18697));
        universities.add(new University("California", "California State University - Chico", 7972, 19852));
        universities.add(new University("California", "California State University - Dominguez Hills", 7060, 18940));
        universities.add(new University("California", "California State University - East Bay", 6995, 18875));
        universities.add(new University("California", "California State University - Fresno", 6663, 18543));
        universities.add(new University("California", "California State University - Fullerton", 7007, 18887));
        universities.add(new University("California", "California State University - Long Beach", 6884, 18764));
        universities.add(new University("California", "California State University - Los Angeles", 6805, 18685));
        universities.add(new University("California", "California State University - Monterey Bay", 7323, 19203));
        universities.add(new University("California", "California State University - Northridge", 7069, 18949));
        universities.add(new University("California", "California State University - Sacramento", 7484, 19364));
        universities.add(new University("California", "California State University - San Bernardino", 7486, 19366));
        universities.add(new University("California", "California State University - San Marcos", 7733, 19613));
        universities.add(new University("California", "California State University - Stanislaus", 7734, 19614));
        universities.add(new University("California", "Career Networks Institute", 75380, 75380));
        universities.add(new University("California", "Casa Loma College - Los Angeles", 41172, 41172));
        universities.add(new University("California", "CBD College", 48728, 48728));
        universities.add(new University("California", "Chamberlain University - California", 20142, 20142));
        universities.add(new University("California", "Chapman University", 60672, 60672));
        universities.add(new University("California", "Charles R Drew University of Medicine and Science", 14954, 14954));
        universities.add(new University("California", "Claremont Lincoln University", 13200, 13200));
        universities.add(new University("California", "Claremont McKenna College", 60715, 60715));
        universities.add(new University("California", "Columbia College Hollywood", 26175, 26175));
        universities.add(new University("California", "Concordia University - Irvine", 40180, 40180));
        universities.add(new University("California", "Cypress College", 1146, 9090));
        universities.add(new University("California", "Design Institute of San Diego", 27875, 27875));
        universities.add(new University("California", "DeVry University - California", 17488, 17488));
        universities.add(new University("California", "Dharma Realm Buddhist University", 21000, 21000));
        universities.add(new University("California", "Dominican University of California", 49426, 49426));
        universities.add(new University("California", "Epic Bible College & Graduate School", 9689, 9689));
        universities.add(new University("California", "Feather River Community College District", 1461, 9531));
        universities.add(new University("California", "FIDM - Fashion Institute of Design & Merchandising", 32645, 32645));
        universities.add(new University("California", "Foothill College", 1565, 11510));
        universities.add(new University("California", "Fremont University", 38288, 38288));
        universities.add(new University("California", "Fresno Pacific University", 34188, 34188));
        universities.add(new University("California", "Glendale Career College", 76757, 76757));
        universities.add(new University("California", "Gnomon", 31065, 31065));
        universities.add(new University("California", "Golden Gate University", 11088, 11088));
        universities.add(new University("California", "Grace Mission University", 3480, 3480));
        universities.add(new University("California", "Gurnick Academy of Medical Arts", 35986, 35986));
        universities.add(new University("California", "Harvey Mudd College", 62817, 62817));
        universities.add(new University("California", "Haven University", 7010, 7010));
        universities.add(new University("California", "Holy Names University", 42115, 42115));
        universities.add(new University("California", "Homestead Schools", 35000, 35000));
        universities.add(new University("California", "Hope International University", 35700, 35700));
        universities.add(new University("California", "Humphreys University - Stockton and Modesto Campuses", 14760, 14760));
        universities.add(new University("California", "Hussian College - Los Angeles", 41923, 41923));
        universities.add(new University("California", "Integrity College of Health", 24980, 24980));
        universities.add(new University("California", "Interior Designers Institute", 20250, 20250));
        universities.add(new University("California", "John Paul the Great Catholic University", 28000, 28000));
        universities.add(new University("California", "La Sierra University", 34902, 34902));
        universities.add(new University("California", "Laguna College of Art and Design", 34600, 34600));
        universities.add(new University("California", "Latin American Bible Institute", 10520, 10520));
        universities.add(new University("California", "Laurus College", 43850, 43850));
        universities.add(new University("California", "Learnet Academy Inc", 13600, 13600));
        universities.add(new University("California", "Life Pacific University", 19140, 19140));
        universities.add(new University("California", "Lincoln University", 11420, 11420));
        universities.add(new University("California", "Lionel University", 15288, 15288));
        universities.add(new University("California", "Loma Linda University", 33552, 33552));
        universities.add(new University("California", "Los Angeles Academy of Figurative Art", 31618, 31618));
        universities.add(new University("California", "Los Angeles College of Music", 25650, 25650));
        universities.add(new University("California", "Los Angeles Film School", 32500, 32500));
        universities.add(new University("California", "Los Angeles Pacific University", 11400, 11400));
        universities.add(new University("California", "Loyola Marymount University", 55926, 55926));
        universities.add(new University("California", "Marymount California University", 36908, 36908));
        universities.add(new University("California", "Menlo College", 49090, 49090));
        universities.add(new University("California", "Middlebury Institute of International Studies at Monterey", 44766, 44766));
        universities.add(new University("California", "Minerva University", 17650, 17650));
        universities.add(new University("California", "MiraCosta College", 1152, 8448));
        universities.add(new University("California", "Modesto Junior College", 1276, 7308));
        universities.add(new University("California", "Mount Saint Mary's University", 46740, 46740));
        universities.add(new University("California", "Musicians Institute", 24795, 24795));
        universities.add(new University("California", "National University", 13320, 13320));
        universities.add(new University("California", "New York Film Academy", 35557, 35557));
        universities.add(new University("California", "Newschool of Architecture and Design", 30291, 30291));
        universities.add(new University("California", "Northcentral University", 11064, 11064));
        universities.add(new University("California", "North-West College-San Diego", 76757, 76757));
        universities.add(new University("California", "Notre Dame de Namur University", 15792, 15792));
        universities.add(new University("California", "Oak Valley College", 16080, 16080));
        universities.add(new University("California", "Occidental College", 60566, 60566));
        universities.add(new University("California", "Otis College of Art and Design", 52460, 52460));
        universities.add(new University("California", "Pacific College", 40000, 40000));
        universities.add(new University("California", "Pacific Oaks College", 11692, 11692));
        universities.add(new University("California", "Pacific States University", 7530, 7530));
        universities.add(new University("California", "Pacific Union College", 33678, 33678));
        universities.add(new University("California", "Palo Alto University", 17714, 17714));
        universities.add(new University("California", "Pathways College", 7056, 7056));
        universities.add(new University("California", "PCI College", 38670, 38670));
        universities.add(new University("California", "Pepperdine University", 63142, 63142));
        universities.add(new University("California", "Pitzer College", 60578, 60578));
        universities.add(new University("California", "Platt College - Anaheim", 14519, 14519));
        universities.add(new University("California", "Platt College - Los Angeles", 14519, 14519));
        universities.add(new University("California", "Platt College - Ontario", 14519, 14519));
        universities.add(new University("California", "Platt College - Riverside", 14519, 14519));
        universities.add(new University("California", "Platt College - San Diego", 15310, 15310));
        universities.add(new University("California", "Point Loma Nazarene University", 41100, 41100));
        universities.add(new University("California", "Pomona College", 59238, 59238));
        universities.add(new University("California", "Presbyterian Theological Seminary in America", 8835, 8835));
        universities.add(new University("California", "Providence Christian College", 33884, 33884));
        universities.add(new University("California", "Reach University", 12374, 12374));
        universities.add(new University("California", "Rio Hondo College", 1388, 9884));
        universities.add(new University("California", "Saint Mary's College of California", 53932, 53932));
        universities.add(new University("California", "Samuel Merritt University", 47931, 47931));
        universities.add(new University("California", "San Diego Christian College", 26300, 26300));
        universities.add(new University("California", "San Diego Global Knowledge University", 17750, 17750));
        universities.add(new University("California", "San Diego Mesa College", 1144, 7440));
        universities.add(new University("California", "San Diego State University", 8174, 20054));
        universities.add(new University("California", "San Francisco Bay University", 8720, 8720));
        universities.add(new University("California", "San Francisco Conservatory of Music", 52800, 52800));
        universities.add(new University("California", "San Francisco State University", 7524, 19404));
        universities.add(new University("California", "San Joaquin Valley College - Visalia", 16802, 16802));
        universities.add(new University("California", "San Jose State University", 7899, 19779));
        universities.add(new University("California", "Santa Ana College", 1180, 8788));
        universities.add(new University("California", "Santa Clara University", 57534, 57534));
        universities.add(new University("California", "Santa Monica College", 1150, 9094));
        universities.add(new University("California", "Scripps College", 60712, 60712));
        universities.add(new University("California", "Shasta Bible College and Graduate School", 14460, 14460));
        universities.add(new University("California", "Shasta College", 1191, 8271));
        universities.add(new University("California", "Simpson University", 37480, 37480));
        universities.add(new University("California", "Skyline College", 1362, 9508));
        universities.add(new University("California", "Smith Chason College", 18820, 18820));
        universities.add(new University("California", "Sofia University", 18000, 18000));
        universities.add(new University("California", "Soka University of America", 35544, 35544));
        universities.add(new University("California", "Solano Community College", 1172, 7628));
        universities.add(new University("California", "Sonoma State University", 8060, 19940));
        universities.add(new University("California", "Southern California Institute of Architecture", 50690, 50690));
        universities.add(new University("California", "Southern California Institute of Technology", 19190, 19190));
        universities.add(new University("California", "Southern California Seminary", 18240, 18240));
        universities.add(new University("California", "Southern California University of Health Sciences", 13215, 13215));
        universities.add(new University("California", "Southern States University", 7439, 7439));
        universities.add(new University("California", "Stanbridge University", 33565, 33565));
        universities.add(new University("California", "Stanford University", 58416, 58416));
        universities.add(new University("California", "SUM Bible College and Theological Seminary", 10730, 10730));
        universities.add(new University("California", "The Chicago School of Professional Psychology at Los Angeles", 13224, 13224));
        universities.add(new University("California", "The Chicago School of Professional Psychology at San Diego", 13224, 13224));
        universities.add(new University("California", "The Master's University and Seminary", 32870, 32870));
        universities.add(new University("California", "Thomas Aquinas College", 27000, 27000));
        universities.add(new University("California", "Touro University Worldwide", 14600, 14600));
        universities.add(new University("California", "United States University", 6630, 6630));
        universities.add(new University("California", "Unitek College", 36630, 36630));
        universities.add(new University("California", "University of Antelope Valley", 67080, 67080));
        universities.add(new University("California", "University of California - Berkeley", 14395, 44467));
        universities.add(new University("California", "University of California - Davis", 14858, 44930));
        universities.add(new University("California", "University of California - Irvine", 13939, 44011));
        universities.add(new University("California", "University of California - Los Angeles", 13401, 43473));
        universities.add(new University("California", "University of California - Merced", 13791, 43863));
        universities.add(new University("California", "University of California - Riverside", 13874, 43946));
        universities.add(new University("California", "University of California - San Diego", 14906, 44978));
        universities.add(new University("California", "University of California - Santa Barbara", 14617, 44689));
        universities.add(new University("California", "University of California - Santa Cruz", 14240, 44312));
        universities.add(new University("California", "University of La Verne", 47000, 47000));
        universities.add(new University("California", "University of Massachusetts Global", 12520, 12520));
        universities.add(new University("California", "University of Phoenix - California", 9552, 9552));
        universities.add(new University("California", "University of Redlands", 55678, 55678));
        universities.add(new University("California", "University of Saint Katherine", 28800, 28800));
        universities.add(new University("California", "University of San Diego", 54554, 54554));
        universities.add(new University("California", "University of San Francisco", 55532, 55532));
        universities.add(new University("California", "University of Silicon Valley", 22480, 22480));
        universities.add(new University("California", "University of Southern California", 64726, 64726));
        universities.add(new University("California", "University of the Pacific", 53682, 53682));
        universities.add(new University("California", "University of the People", 1200, 1200));
        universities.add(new University("California", "University of the West", 14018, 14018));
        universities.add(new University("California", "University of West Los Angeles", 6960, 6960));
        universities.add(new University("California", "Vanguard University of Southern California", 38700, 38700));
        universities.add(new University("California", "West Coast University - Los Angeles", 36140, 36140));
        universities.add(new University("California", "West Coast University - Ontario", 36140, 36140));
        universities.add(new University("California", "West Coast University - Orange County", 22889, 22889));
        universities.add(new University("California", "West Los Angeles College", 1238, 9870));
        universities.add(new University("California", "Westcliff University", 17550, 17550));
        universities.add(new University("California", "Westmont College", 50066, 50066));
        universities.add(new University("California", "Whittier College", 49864, 49864));
        universities.add(new University("California", "William Jessup University", 37150, 37150));
        universities.add(new University("California", "Woodbury University", 44908, 44908));
        universities.add(new University("California", "World Mission University", 6680, 6680));
        universities.add(new University("California", "Yeshiva Ohr Elchonon Chabad West Coast Talmudical Seminary", 15700, 15700));
        universities.add(new University("Colorado", "Adams State University", 9776, 21848));
        universities.add(new University("Colorado", "Arapahoe Community College", 4080, 15502));
        universities.add(new University("Colorado", "Colorado Christian University", 37432, 37432));
        universities.add(new University("Colorado", "Colorado College", 65028, 65028));
        universities.add(new University("Colorado", "Colorado Mesa University", 9297, 23019));
        universities.add(new University("Colorado", "Colorado Mountain College", 4980, 11820));
        universities.add(new University("Colorado", "Colorado School of Mines", 20040, 42120));
        universities.add(new University("Colorado", "Colorado State University Global", 8400, 8400));
        universities.add(new University("Colorado", "Colorado State University Pueblo", 9245, 16324));
        universities.add(new University("Colorado", "Colorado State University - Fort Collins", 12874, 32734));
        universities.add(new University("Colorado", "Colorado Technical University - Colorado Springs", 12696, 12696));
        universities.add(new University("Colorado", "Community College of Denver", 4586, 16235));
        universities.add(new University("Colorado", "Concorde Career College - Aurora", 16434, 16434));
        universities.add(new University("Colorado", "Denver College of Nursing", 10759, 10759));
        universities.add(new University("Colorado", "DeVry University - Colorado", 17488, 17488));
        universities.add(new University("Colorado", "Fort Lewis College", 9212, 19724));
        universities.add(new University("Colorado", "Front Range Community College", 4126, 15776));
        universities.add(new University("Colorado", "Metropolitan State University of Denver", 10260, 28092));
        universities.add(new University("Colorado", "Morgan Community College", 3930, 15579));
        universities.add(new University("Colorado", "Naropa University", 34600, 34600));
        universities.add(new University("Colorado", "Nazarene Bible College", 10002, 10002));
        universities.add(new University("Colorado", "Pikes Peak State College", 4065, 15714));
        universities.add(new University("Colorado", "Platt College - Aurora", 20590, 20590));
        universities.add(new University("Colorado", "Pueblo Community College", 4626, 16275));
        universities.add(new University("Colorado", "Red Rocks Community College", 4471, 16135));
        universities.add(new University("Colorado", "Regis University", 42220, 42220));
        universities.add(new University("Colorado", "Rocky Mountain College of Art and Design", 22607, 22607));
        universities.add(new University("Colorado", "Taft University System", 3600, 3600));
        universities.add(new University("Colorado", "Trinidad State College", 5194, 8314));
        universities.add(new University("Colorado", "University of Colorado Boulder", 13106, 40356));
        universities.add(new University("Colorado", "University of Colorado Colorado Springs", 9129, 22041));
        universities.add(new University("Colorado", "University of Colorado Denver/Anschutz Medical Campus", 9562, 26818));
        universities.add(new University("Colorado", "University of Denver", 56439, 56439));
        universities.add(new University("Colorado", "University of Northern Colorado", 11332, 24722));
        universities.add(new University("Colorado", "Western Colorado University", 10813, 22837));
        universities.add(new University("Connecticut", "Albertus Magnus College", 37682, 37682));
        universities.add(new University("Connecticut", "Central Connecticut State University", 12106, 24994));
        universities.add(new University("Connecticut", "Charter Oak State College", 8254, 10796));
        universities.add(new University("Connecticut", "Connecticut College", 63005, 63005));
        universities.add(new University("Connecticut", "Eastern Connecticut State University", 12910, 16146));
        universities.add(new University("Connecticut", "Fairfield University", 54455, 54455));
        universities.add(new University("Connecticut", "Goodwin University", 21198, 21198));
        universities.add(new University("Connecticut", "Holy Apostles College and Seminary", 9440, 9440));
        universities.add(new University("Connecticut", "Mitchell College", 37250, 37250));
        universities.add(new University("Connecticut", "Paier College", 24480, 24480));
        universities.add(new University("Connecticut", "Post University", 16610, 16610));
        universities.add(new University("Connecticut", "Quinnipiac University", 51790, 51790));
        universities.add(new University("Connecticut", "Sacred Heart University", 46580, 46580));
        universities.add(new University("Connecticut", "Southern Connecticut State University", 12438, 25326));
        universities.add(new University("Connecticut", "Trinity College", 63930, 63930));
        universities.add(new University("Connecticut", "University of Bridgeport", 35760, 35760));
        universities.add(new University("Connecticut", "University of Connecticut", 19434, 42102));
        universities.add(new University("Connecticut", "University of Hartford", 46148, 46148));
        universities.add(new University("Connecticut", "University of New Haven", 44184, 44184));
        universities.add(new University("Connecticut", "University of Saint Joseph", 44366, 44366));
        universities.add(new University("Connecticut", "Wesleyan University", 64322, 64322));
        universities.add(new University("Connecticut", "Western Connecticut State University", 12345, 25239));
        universities.add(new University("Connecticut", "Yale University", 62250, 62250));
    }
}

