package com.example.googlemapspractice;

import java.util.ArrayList;
import java.util.List;

public class UniversityData {
    public static void main(String[] args) {
        List<University> universities = new ArrayList<>();

        universities.add(new University("Alabama", "Alabama A & M University", 10024, 18634));
        universities.add(new University("Alabama", "Alabama State University", 11068, 19396));
        universities.add(new University("Alabama", "Amridge University", 9000, 9000));
        universities.add(new University("Alabama", "Athens State University", 7230, 14460));
        universities.add(new University("Alabama", "Auburn University", 12176, 32960));
        universities.add(new University("Alabama", "Auburn University at Montgomery", 9100, 19348));
        universities.add(new University("Alabama", "Birmingham-Southern College", 21250, 21250));
        universities.add(new University("Alabama", "Columbia Southern University", 6015, 6015));
        universities.add(new University("Alabama", "Faulkner University", 23920, 23920));
        universities.add(new University("Alabama", "Heritage Christian University", 11632, 11632));
        universities.add(new University("Alabama", "Herzing University-Birmingham", 12750, 12750));
        universities.add(new University("Alabama", "Huntingdon College", 28350, 28350));
        universities.add(new University("Alabama", "Huntsville Bible College", 4730, 4730));
        universities.add(new University("Alabama", "Jacksonville State University", 11952, 21912));
        universities.add(new University("Alabama", "Miles College", 12714, 12714));
        universities.add(new University("Alabama", "Oakwood University", 20040, 20040));
        universities.add(new University("Alabama", "Samford University", 36725, 36725));
        universities.add(new University("Alabama", "Selma University", 4800, 4800));
        universities.add(new University("Alabama", "South University-Montgomery", 17014, 17014));
        universities.add(new University("Alabama", "Spring Hill College", 21732, 21732));
        universities.add(new University("Alabama", "Stillman College", 11392, 11392));
        universities.add(new University("Alabama", "Strayer University-Alabama", 13515, 13515));
        universities.add(new University("Alabama", "Talladega College", 13866, 13866));
        universities.add(new University("Alabama", "The University of Alabama", 11940, 32300));
        universities.add(new University("Alabama", "Troy University", 9312, 18624));
        universities.add(new University("Alabama", "Tuskegee University", 22614, 22614));
        universities.add(new University("Alabama", "United States Sports Academy", 16418, 16418));
        universities.add(new University("Alabama", "University of Alabama at Birmingham", 8832, 21216));
        universities.add(new University("Alabama", "University of Alabama in Huntsville", 11878, 24770));
        universities.add(new University("Alabama", "University of Mobile", 25880, 25880));
        universities.add(new University("Alabama", "University of Montevallo", 13710, 26730));
        universities.add(new University("Alabama", "University of North Alabama", 11220, 21420));
        universities.add(new University("Alabama", "University of South Alabama", 9116, 17732));
        universities.add(new University("Alabama", "University of West Alabama", 10990, 20090));
        universities.add(new University("Alaska", "Alaska Bible College", 10900, 10900));
        universities.add(new University("Alaska", "Alaska Pacific University", 20760, 20760));
        universities.add(new University("Alaska", "Ilisagvik College", 5260, 5260));
        universities.add(new University("Alaska", "University of Alaska Anchorage", 7508, 21635));
        universities.add(new University("Alaska", "University of Alaska Fairbanks", 7896, 22032));
        universities.add(new University("Alaska", "University of Alaska Southeast", 6960, 21096));
        universities.add(new University("Arizona", "American InterContinental University", 12422, 12422));
        universities.add(new University("Arizona", "Arizona Christian University", 31650, 31650));
        universities.add(new University("Arizona", "Arizona College of Nursing - Phoenix", 24000, 24000));
        universities.add(new University("Arizona", "Arizona College of Nursing - Tempe", 24000, 24000));
        universities.add(new University("Arizona", "Arizona College of Nursing - Tucson", 22826, 22826));
        universities.add(new University("Arizona", "Arizona State University Campus Immersion", 11618, 30592));
        universities.add(new University("Arizona", "Arizona State University Digital Immersion", 10978, 13248));
        universities.add(new University("Arizona", "Aspen University", 5355, 5355));
        universities.add(new University("Arizona", "Brookline College - Phoenix", 89404, 89404));
        universities.add(new University("Arizona", "Brookline College - Tempe", 30150, 30150));
        universities.add(new University("Arizona", "Brookline College - Tucson", 31150, 31150));
        universities.add(new University("Arizona", "Bryan University", 12184, 12184));
        universities.add(new University("Arizona", "Chamberlain University - Arizona", 20142, 20142));
        universities.add(new University("Arizona", "DeVry University - Arizona", 17488, 17488));
        universities.add(new University("Arizona", "Dine College", 1410, 1410));
        universities.add(new University("Arizona", "Embry-Riddle Aeronautical University - Prescott", 40464, 40464));
        universities.add(new University("Arizona", "Grand Canyon University", 17800, 17800));
        universities.add(new University("Arizona", "Indian Bible College", 7420, 7420));
        universities.add(new University("Arizona", "International Baptist College and Seminary", 13200, 13200));
        universities.add(new University("Arizona", "National Paralegal College", 7995, 7995));
        universities.add(new University("Arizona", "Northern Arizona University", 12274, 27536));
        universities.add(new University("Arizona", "Ottawa University - Phoenix", 12641, 12641));
        universities.add(new University("Arizona", "Ottawa University - Surprise", 33000, 33000));
        universities.add(new University("Arizona", "Pima Medical Institute - Tucson", 24475, 24475));
        universities.add(new University("Arizona", "Prescott College", 35450, 35450));
        universities.add(new University("Arizona", "Sessions College for Professional Design", 12440, 12440));
        universities.add(new University("Arizona", "University of Advancing Technology", 18794, 18794));
        universities.add(new University("Arizona", "University of Arizona", 13275, 39577));
        universities.add(new University("Arizona", "University of Phoenix - Arizona", 9552, 9552));
        universities.add(new University("Arkansas", "Arkansas Baptist College", 8760, 8760));
        universities.add(new University("Arkansas", "Arkansas State University", 7456, 13312));
        universities.add(new University("Arkansas", "Arkansas Tech University", 8071, 13891));
        universities.add(new University("Arkansas", "Central Baptist College", 17700, 17700));
        universities.add(new University("Arkansas", "Champion Christian College", 7755, 7755));
        universities.add(new University("Arkansas", "Crowley's Ridge College", 15000, 15000));
        universities.add(new University("Arkansas", "Ecclesia College", 16850, 16850));
        universities.add(new University("Arkansas", "Harding University", 23148, 23148));
        universities.add(new University("Arkansas", "Henderson State University", 7560, 9768));
        universities.add(new University("Arkansas", "Hendrix College", 35100, 35100));
        universities.add(new University("Arkansas", "Jackson Theological Seminary", 6000, 6000));
        universities.add(new University("Arkansas", "John Brown University", 29720, 29720));
        universities.add(new University("Arkansas", "Lyon College", 31000, 31000));
        universities.add(new University("Arkansas", "Ouachita Baptist University", 31180, 31180));
        universities.add(new University("Arkansas", "Philander Smith College", 13014, 13014));
        universities.add(new University("Arkansas", "Southern Arkansas University Main Campus", 9680, 15110));
        universities.add(new University("Arkansas", "Strayer University - Arkansas", 13515, 13515));
        universities.add(new University("Arkansas", "University of Arkansas", 9656, 27410));
        universities.add(new University("Arkansas", "University of Arkansas at Little Rock", 8366, 18957));
        universities.add(new University("Arkansas", "University of Arkansas at Monticello", 8431, 14281));
        universities.add(new University("Arkansas", "University of Arkansas at Pine Bluff", 8668, 15838));
        universities.add(new University("Arkansas", "University of Arkansas for Medical Sciences", 7068, 14586));
        universities.add(new University("Arkansas", "University of Arkansas Grantham", 8280, 8280));
        universities.add(new University("Arkansas", "University of Arkansas - Fort Smith", 6168, 13440));
        universities.add(new University("Arkansas", "University of Central Arkansas", 9778, 16728));
        universities.add(new University("Arkansas", "University of the Ozarks", 25950, 25950));
        universities.add(new University("Arkansas", "Williams Baptist University", 19450, 19450));
        universities.add(new University("California", "Abraham Lincoln University", 6480, 6480));
        universities.add(new University("California", "Academy of Art University", 26728, 26728));
        universities.add(new University("California", "Agape College of Business and Science", 7942, 7942));
        universities.add(new University("California", "Alliant International University - San Diego", 13680, 13680));
        universities.add(new University("California", "America Evangelical University", 6200, 6200));
        universities.add(new University("California", "American Jewish University", 9720, 9720));
        universities.add(new University("California", "American Medical Sciences Center", 39097, 39097));
        universities.add(new University("California", "American University of Health Sciences", 24575, 24575));
        universities.add(new University("California", "Angeles College", 30010, 30010));
        universities.add(new University("California", "Antelope Valley Community College District", 1124, 7724));
        universities.add(new University("California", "Antioch University - Los Angeles", 16050, 16050));
        universities.add(new University("California", "Antioch University - Santa Barbara", 17820, 17820));
        universities.add(new University("California", "Arizona College - Ontario", 29146, 29146));
        universities.add(new University("California", "Art Center College of Design", 49942, 49942));
        universities.add(new University("California", "Ashford University", 13160, 13160));
        universities.add(new University("California", "ATI College-Whittier", 34900, 34900));
        universities.add(new University("California", "Azusa Pacific University", 42330, 42330));
        universities.add(new University("California", "Bakersfield College", 1430, 9560));
        universities.add(new University("California", "Bergin University of Canine Studies", 9993, 9993));
        universities.add(new University("California", "Bethesda University", 6560, 6560));
        universities.add(new University("California", "Beverly Hills Design Institute", 23220, 23220));
        universities.add(new University("California", "Biola University", 44382, 44382));
        universities.add(new University("California", "California Aeronautical University", 33037, 33037));
        universities.add(new University("California", "California Baptist University", 38058, 38058));
        universities.add(new University("California", "California Christian College", 10890, 10890));
        universities.add(new University("California", "California College of the Arts", 54706, 54706));
        universities.add(new University("California", "California Institute of Integral Studies", 21116, 21116));
        universities.add(new University("California", "California Institute of Technology", 60864, 60864));
        universities.add(new University("California", "California Institute of the Arts", 55056, 55056));
        universities.add(new University("California", "California Intercontinental University", 9054, 9054));
        universities.add(new University("California", "California Jazz Conservatory", 22800, 22800));
        universities.add(new University("California", "California Lutheran University", 48012, 48012));
        universities.add(new University("California", "California Miramar University", 9994, 9994));
        universities.add(new University("California", "California Northstate University", 52685, 52685));
        universities.add(new University("California", "California Polytechnic State University - San Luis Obispo", 10319, 28229));
        universities.add(new University("California", "California State Polytechnic University - Humboldt", 7864, 19744));
        universities.add(new University("California", "California State Polytechnic University - Pomona", 7439, 19319));
        universities.add(new University("California", "California State University Maritime Academy", 7116, 18996));
        universities.add(new University("California", "California State University - Bakersfield", 7637, 19517));
        universities.add(new University("California", "California State University - Channel Islands", 6817, 18697));
        universities.add(new University("California", "California State University - Chico", 7972, 19852));
        universities.add(new University("California", "California State University - Dominguez Hills", 7060, 18940));
        universities.add(new University("California", "California State University - East Bay", 6995, 18875));
        universities.add(new University("California", "California State University - Fresno", 6663, 18543));
        universities.add(new University("California", "California State University - Fullerton", 7007, 18887));
        universities.add(new University("California", "California State University - Long Beach", 6884, 18764));
        universities.add(new University("California", "California State University - Los Angeles", 6805, 18685));
        universities.add(new University("California", "California State University - Monterey Bay", 7323, 19203));
        universities.add(new University("California", "California State University - Northridge", 7069, 18949));
        universities.add(new University("California", "California State University - Sacramento", 7484, 19364));
        universities.add(new University("California", "California State University - San Bernardino", 7486, 19366));
        universities.add(new University("California", "California State University - San Marcos", 7733, 19613));
        universities.add(new University("California", "California State University - Stanislaus", 7734, 19614));
        universities.add(new University("California", "Career Networks Institute", 75380, 75380));
        universities.add(new University("California", "Casa Loma College - Los Angeles", 41172, 41172));
        universities.add(new University("California", "CBD College", 48728, 48728));
        universities.add(new University("California", "Chamberlain University - California", 20142, 20142));
        universities.add(new University("California", "Chapman University", 60672, 60672));
        universities.add(new University("California", "Charles R Drew University of Medicine and Science", 14954, 14954));
        universities.add(new University("California", "Claremont Lincoln University", 13200, 13200));
        universities.add(new University("California", "Claremont McKenna College", 60715, 60715));
        universities.add(new University("California", "Columbia College Hollywood", 26175, 26175));
        universities.add(new University("California", "Concordia University - Irvine", 40180, 40180));
        universities.add(new University("California", "Cypress College", 1146, 9090));
        universities.add(new University("California", "Design Institute of San Diego", 27875, 27875));
        universities.add(new University("California", "DeVry University - California", 17488, 17488));
        universities.add(new University("California", "Dharma Realm Buddhist University", 21000, 21000));
        universities.add(new University("California", "Dominican University of California", 49426, 49426));
        universities.add(new University("California", "Epic Bible College & Graduate School", 9689, 9689));
        universities.add(new University("California", "Feather River Community College District", 1461, 9531));
        universities.add(new University("California", "FIDM - Fashion Institute of Design & Merchandising", 32645, 32645));
        universities.add(new University("California", "Foothill College", 1565, 11510));
        universities.add(new University("California", "Fremont University", 38288, 38288));
        universities.add(new University("California", "Fresno Pacific University", 34188, 34188));
        universities.add(new University("California", "Glendale Career College", 76757, 76757));
        universities.add(new University("California", "Gnomon", 31065, 31065));
        universities.add(new University("California", "Golden Gate University", 11088, 11088));
        universities.add(new University("California", "Grace Mission University", 3480, 3480));
        universities.add(new University("California", "Gurnick Academy of Medical Arts", 35986, 35986));
        universities.add(new University("California", "Harvey Mudd College", 62817, 62817));
        universities.add(new University("California", "Haven University", 7010, 7010));
        universities.add(new University("California", "Holy Names University", 42115, 42115));
        universities.add(new University("California", "Homestead Schools", 35000, 35000));
        universities.add(new University("California", "Hope International University", 35700, 35700));
        universities.add(new University("California", "Humphreys University - Stockton and Modesto Campuses", 14760, 14760));
        universities.add(new University("California", "Hussian College - Los Angeles", 41923, 41923));
        universities.add(new University("California", "Integrity College of Health", 24980, 24980));
        universities.add(new University("California", "Interior Designers Institute", 20250, 20250));
        universities.add(new University("California", "John Paul the Great Catholic University", 28000, 28000));
        universities.add(new University("California", "La Sierra University", 34902, 34902));
        universities.add(new University("California", "Laguna College of Art and Design", 34600, 34600));
        universities.add(new University("California", "Latin American Bible Institute", 10520, 10520));
        universities.add(new University("California", "Laurus College", 43850, 43850));
        universities.add(new University("California", "Learnet Academy Inc", 13600, 13600));
        universities.add(new University("California", "Life Pacific University", 19140, 19140));
        universities.add(new University("California", "Lincoln University", 11420, 11420));
        universities.add(new University("California", "Lionel University", 15288, 15288));
        universities.add(new University("California", "Loma Linda University", 33552, 33552));
        universities.add(new University("California", "Los Angeles Academy of Figurative Art", 31618, 31618));
        universities.add(new University("California", "Los Angeles College of Music", 25650, 25650));
        universities.add(new University("California", "Los Angeles Film School", 32500, 32500));
        universities.add(new University("California", "Los Angeles Pacific University", 11400, 11400));
        universities.add(new University("California", "Loyola Marymount University", 55926, 55926));
        universities.add(new University("California", "Marymount California University", 36908, 36908));
        universities.add(new University("California", "Menlo College", 49090, 49090));
        universities.add(new University("California", "Middlebury Institute of International Studies at Monterey", 44766, 44766));
        universities.add(new University("California", "Minerva University", 17650, 17650));
        universities.add(new University("California", "MiraCosta College", 1152, 8448));
        universities.add(new University("California", "Modesto Junior College", 1276, 7308));
        universities.add(new University("California", "Mount Saint Mary's University", 46740, 46740));
        universities.add(new University("California", "Musicians Institute", 24795, 24795));
        universities.add(new University("California", "National University", 13320, 13320));
        universities.add(new University("California", "New York Film Academy", 35557, 35557));
        universities.add(new University("California", "Newschool of Architecture and Design", 30291, 30291));
        universities.add(new University("California", "Northcentral University", 11064, 11064));
        universities.add(new University("California", "North-West College-San Diego", 76757, 76757));
        universities.add(new University("California", "Notre Dame de Namur University", 15792, 15792));
        universities.add(new University("California", "Oak Valley College", 16080, 16080));
        universities.add(new University("California", "Occidental College", 60566, 60566));
        universities.add(new University("California", "Otis College of Art and Design", 52460, 52460));
        universities.add(new University("California", "Pacific College", 40000, 40000));
        universities.add(new University("California", "Pacific Oaks College", 11692, 11692));
        universities.add(new University("California", "Pacific States University", 7530, 7530));
        universities.add(new University("California", "Pacific Union College", 33678, 33678));
        universities.add(new University("California", "Palo Alto University", 17714, 17714));
        universities.add(new University("California", "Pathways College", 7056, 7056));
        universities.add(new University("California", "PCI College", 38670, 38670));
        universities.add(new University("California", "Pepperdine University", 63142, 63142));
        universities.add(new University("California", "Pitzer College", 60578, 60578));
        universities.add(new University("California", "Platt College - Anaheim", 14519, 14519));
        universities.add(new University("California", "Platt College - Los Angeles", 14519, 14519));
        universities.add(new University("California", "Platt College - Ontario", 14519, 14519));
        universities.add(new University("California", "Platt College - Riverside", 14519, 14519));
        universities.add(new University("California", "Platt College - San Diego", 15310, 15310));
        universities.add(new University("California", "Point Loma Nazarene University", 41100, 41100));
        universities.add(new University("California", "Pomona College", 59238, 59238));
        universities.add(new University("California", "Presbyterian Theological Seminary in America", 8835, 8835));
        universities.add(new University("California", "Providence Christian College", 33884, 33884));
        universities.add(new University("California", "Reach University", 12374, 12374));
        universities.add(new University("California", "Rio Hondo College", 1388, 9884));
        universities.add(new University("California", "Saint Mary's College of California", 53932, 53932));
        universities.add(new University("California", "Samuel Merritt University", 47931, 47931));
        universities.add(new University("California", "San Diego Christian College", 26300, 26300));
        universities.add(new University("California", "San Diego Global Knowledge University", 17750, 17750));
        universities.add(new University("California", "San Diego Mesa College", 1144, 7440));
        universities.add(new University("California", "San Diego State University", 8174, 20054));
        universities.add(new University("California", "San Francisco Bay University", 8720, 8720));
        universities.add(new University("California", "San Francisco Conservatory of Music", 52800, 52800));
        universities.add(new University("California", "San Francisco State University", 7524, 19404));
        universities.add(new University("California", "San Joaquin Valley College - Visalia", 16802, 16802));
        universities.add(new University("California", "San Jose State University", 7899, 19779));
        universities.add(new University("California", "Santa Ana College", 1180, 8788));
        universities.add(new University("California", "Santa Clara University", 57534, 57534));
        universities.add(new University("California", "Santa Monica College", 1150, 9094));
        universities.add(new University("California", "Scripps College", 60712, 60712));
        universities.add(new University("California", "Shasta Bible College and Graduate School", 14460, 14460));
        universities.add(new University("California", "Shasta College", 1191, 8271));
        universities.add(new University("California", "Simpson University", 37480, 37480));
        universities.add(new University("California", "Skyline College", 1362, 9508));
        universities.add(new University("California", "Smith Chason College", 18820, 18820));
        universities.add(new University("California", "Sofia University", 18000, 18000));
        universities.add(new University("California", "Soka University of America", 35544, 35544));
        universities.add(new University("California", "Solano Community College", 1172, 7628));
        universities.add(new University("California", "Sonoma State University", 8060, 19940));
        universities.add(new University("California", "Southern California Institute of Architecture", 50690, 50690));
        universities.add(new University("California", "Southern California Institute of Technology", 19190, 19190));
        universities.add(new University("California", "Southern California Seminary", 18240, 18240));
        universities.add(new University("California", "Southern California University of Health Sciences", 13215, 13215));
        universities.add(new University("California", "Southern States University", 7439, 7439));
        universities.add(new University("California", "Stanbridge University", 33565, 33565));
        universities.add(new University("California", "Stanford University", 58416, 58416));
        universities.add(new University("California", "SUM Bible College and Theological Seminary", 10730, 10730));
        universities.add(new University("California", "The Chicago School of Professional Psychology at Los Angeles", 13224, 13224));
        universities.add(new University("California", "The Chicago School of Professional Psychology at San Diego", 13224, 13224));
        universities.add(new University("California", "The Master's University and Seminary", 32870, 32870));
        universities.add(new University("California", "Thomas Aquinas College", 27000, 27000));
        universities.add(new University("California", "Touro University Worldwide", 14600, 14600));
        universities.add(new University("California", "United States University", 6630, 6630));
        universities.add(new University("California", "Unitek College", 36630, 36630));
        universities.add(new University("California", "University of Antelope Valley", 67080, 67080));
        universities.add(new University("California", "University of California - Berkeley", 14395, 44467));
        universities.add(new University("California", "University of California - Davis", 14858, 44930));
        universities.add(new University("California", "University of California - Irvine", 13939, 44011));
        universities.add(new University("California", "University of California - Los Angeles", 13401, 43473));
        universities.add(new University("California", "University of California - Merced", 13791, 43863));
        universities.add(new University("California", "University of California - Riverside", 13874, 43946));
        universities.add(new University("California", "University of California - San Diego", 14906, 44978));
        universities.add(new University("California", "University of California - Santa Barbara", 14617, 44689));
        universities.add(new University("California", "University of California - Santa Cruz", 14240, 44312));
        universities.add(new University("California", "University of La Verne", 47000, 47000));
        universities.add(new University("California", "University of Massachusetts Global", 12520, 12520));
        universities.add(new University("California", "University of Phoenix - California", 9552, 9552));
        universities.add(new University("California", "University of Redlands", 55678, 55678));
        universities.add(new University("California", "University of Saint Katherine", 28800, 28800));
        universities.add(new University("California", "University of San Diego", 54554, 54554));
        universities.add(new University("California", "University of San Francisco", 55532, 55532));
        universities.add(new University("California", "University of Silicon Valley", 22480, 22480));
        universities.add(new University("California", "University of Southern California", 64726, 64726));
        universities.add(new University("California", "University of the Pacific", 53682, 53682));
        universities.add(new University("California", "University of the People", 1200, 1200));
        universities.add(new University("California", "University of the West", 14018, 14018));
        universities.add(new University("California", "University of West Los Angeles", 6960, 6960));
        universities.add(new University("California", "Vanguard University of Southern California", 38700, 38700));
        universities.add(new University("California", "West Coast University - Los Angeles", 36140, 36140));
        universities.add(new University("California", "West Coast University - Ontario", 36140, 36140));
        universities.add(new University("California", "West Coast University - Orange County", 22889, 22889));
        universities.add(new University("California", "West Los Angeles College", 1238, 9870));
        universities.add(new University("California", "Westcliff University", 17550, 17550));
        universities.add(new University("California", "Westmont College", 50066, 50066));
        universities.add(new University("California", "Whittier College", 49864, 49864));
        universities.add(new University("California", "William Jessup University", 37150, 37150));
        universities.add(new University("California", "Woodbury University", 44908, 44908));
        universities.add(new University("California", "World Mission University", 6680, 6680));
        universities.add(new University("California", "Yeshiva Ohr Elchonon Chabad West Coast Talmudical Seminary", 15700, 15700));
        universities.add(new University("Colorado", "Adams State University", 9776, 21848));
        universities.add(new University("Colorado", "Arapahoe Community College", 4080, 15502));
        universities.add(new University("Colorado", "Colorado Christian University", 37432, 37432));
        universities.add(new University("Colorado", "Colorado College", 65028, 65028));
        universities.add(new University("Colorado", "Colorado Mesa University", 9297, 23019));
        universities.add(new University("Colorado", "Colorado Mountain College", 4980, 11820));
        universities.add(new University("Colorado", "Colorado School of Mines", 20040, 42120));
        universities.add(new University("Colorado", "Colorado State University Global", 8400, 8400));
        universities.add(new University("Colorado", "Colorado State University Pueblo", 9245, 16324));
        universities.add(new University("Colorado", "Colorado State University - Fort Collins", 12874, 32734));
        universities.add(new University("Colorado", "Colorado Technical University - Colorado Springs", 12696, 12696));
        universities.add(new University("Colorado", "Community College of Denver", 4586, 16235));
        universities.add(new University("Colorado", "Concorde Career College - Aurora", 16434, 16434));
        universities.add(new University("Colorado", "Denver College of Nursing", 10759, 10759));
        universities.add(new University("Colorado", "DeVry University - Colorado", 17488, 17488));
        universities.add(new University("Colorado", "Fort Lewis College", 9212, 19724));
        universities.add(new University("Colorado", "Front Range Community College", 4126, 15776));
        universities.add(new University("Colorado", "Metropolitan State University of Denver", 10260, 28092));
        universities.add(new University("Colorado", "Morgan Community College", 3930, 15579));
        universities.add(new University("Colorado", "Naropa University", 34600, 34600));
        universities.add(new University("Colorado", "Nazarene Bible College", 10002, 10002));
        universities.add(new University("Colorado", "Pikes Peak State College", 4065, 15714));
        universities.add(new University("Colorado", "Platt College - Aurora", 20590, 20590));
        universities.add(new University("Colorado", "Pueblo Community College", 4626, 16275));
        universities.add(new University("Colorado", "Red Rocks Community College", 4471, 16135));
        universities.add(new University("Colorado", "Regis University", 42220, 42220));
        universities.add(new University("Colorado", "Rocky Mountain College of Art and Design", 22607, 22607));
        universities.add(new University("Colorado", "Taft University System", 3600, 3600));
        universities.add(new University("Colorado", "Trinidad State College", 5194, 8314));
        universities.add(new University("Colorado", "University of Colorado Boulder", 13106, 40356));
        universities.add(new University("Colorado", "University of Colorado Colorado Springs", 9129, 22041));
        universities.add(new University("Colorado", "University of Colorado Denver/Anschutz Medical Campus", 9562, 26818));
        universities.add(new University("Colorado", "University of Denver", 56439, 56439));
        universities.add(new University("Colorado", "University of Northern Colorado", 11332, 24722));
        universities.add(new University("Colorado", "Western Colorado University", 10813, 22837));
        universities.add(new University("Connecticut", "Albertus Magnus College", 37682, 37682));
        universities.add(new University("Connecticut", "Central Connecticut State University", 12106, 24994));
        universities.add(new University("Connecticut", "Charter Oak State College", 8254, 10796));
        universities.add(new University("Connecticut", "Connecticut College", 63005, 63005));
        universities.add(new University("Connecticut", "Eastern Connecticut State University", 12910, 16146));
        universities.add(new University("Connecticut", "Fairfield University", 54455, 54455));
        universities.add(new University("Connecticut", "Goodwin University", 21198, 21198));
        universities.add(new University("Connecticut", "Holy Apostles College and Seminary", 9440, 9440));
        universities.add(new University("Connecticut", "Mitchell College", 37250, 37250));
        universities.add(new University("Connecticut", "Paier College", 24480, 24480));
        universities.add(new University("Connecticut", "Post University", 16610, 16610));
        universities.add(new University("Connecticut", "Quinnipiac University", 51790, 51790));
        universities.add(new University("Connecticut", "Sacred Heart University", 46580, 46580));
        universities.add(new University("Connecticut", "Southern Connecticut State University", 12438, 25326));
        universities.add(new University("Connecticut", "Trinity College", 63930, 63930));
        universities.add(new University("Connecticut", "University of Bridgeport", 35760, 35760));
        universities.add(new University("Connecticut", "University of Connecticut", 19434, 42102));
        universities.add(new University("Connecticut", "University of Hartford", 46148, 46148));
        universities.add(new University("Connecticut", "University of New Haven", 44184, 44184));
        universities.add(new University("Connecticut", "University of Saint Joseph", 44366, 44366));
        universities.add(new University("Connecticut", "Wesleyan University", 64322, 64322));
        universities.add(new University("Connecticut", "Western Connecticut State University", 12345, 25239));
        universities.add(new University("Connecticut", "Yale University", 62250, 62250));
        universities.add(new University("Delaware", "Delaware State University", 8358, 18280));
        universities.add(new University("Delaware", "Delaware Technical Community College - Terry", 4945, 11808));
        universities.add(new University("Delaware", "Goldey - Beacom College", 13050, 13050));
        universities.add(new University("Delaware", "Strayer University - Delaware", 13515, 13515));
        universities.add(new University("Delaware", "University of Delaware", 15410, 37930));
        universities.add(new University("Delaware", "Wilmington University", 12030, 12030));
        universities.add(new University("District of Columbia", "American University", 53889, 53889));
        universities.add(new University("District of Columbia", "Gallaudet University", 17712, 17712));
        universities.add(new University("District of Columbia", "George Washington University", 62200, 62200));
        universities.add(new University("District of Columbia", "Georgetown University", 62052, 62052));
        universities.add(new University("District of Columbia", "Howard University", 31050, 31050));
        universities.add(new University("District of Columbia", "NewU University", 16500, 16500));
        universities.add(new University("District of Columbia", "Strayer University - District of Columbia", 13515, 13515));
        universities.add(new University("District of Columbia", "Strayer University - Global Region", 13515, 13515));
        universities.add(new University("District of Columbia", "The Catholic University of America", 54186, 54186));
        universities.add(new University("District of Columbia", "Trinity Washington University", 25610, 25610));
        universities.add(new University("District of Columbia", "University of the District of Columbia", 6152, 13004));
        universities.add(new University("District of Columbia", "University of the Potomac - Washington DC Campus", 6660, 6660));
        //Florida
        universities.add(new University("Georgia", "Abraham Baldwin Agricultural College", 3165, 10071));
        universities.add(new University("Georgia", "Agnes Scott College", 45786, 45786));
        universities.add(new University("Georgia", "Albany State University", 5484, 16206));
        universities.add(new University("Georgia", "Albany Technical College", 2996, 5396));
        universities.add(new University("Georgia", "Altierus Career College-Norcross", 15060, 15060));
        universities.add(new University("Georgia", "American InterContinental University-Atlanta", 13267, 13267));
        universities.add(new University("Georgia", "Andrew College", 18214, 18214));
        universities.add(new University("Georgia", "Athens Technical College", 3062, 5462));
        universities.add(new University("Georgia", "Atlanta Institute of Music and Media", 41100, 41100));
        universities.add(new University("Georgia", "Atlanta Metropolitan State College", 3106, 9731));
        universities.add(new University("Georgia", "Atlanta School of Massage", 13587, 13587));
        universities.add(new University("Georgia", "Atlanta Technical College", 3164, 5564));
        universities.add(new University("Georgia", "Augusta School of Massage", 10500, 10500));
        universities.add(new University("Georgia", "Augusta Technical College", 3262, 5662));
        universities.add(new University("Georgia", "Augusta University", 8122, 23500));
        universities.add(new University("Georgia", "Aviation Institute of Maintenance-Atlanta", 16657, 16657));
        universities.add(new University("Georgia", "Berry College", 39376, 39376));
        universities.add(new University("Georgia", "Beulah Heights University", 8492, 8492));
        universities.add(new University("Georgia", "Brenau University", 32685, 32685));
        universities.add(new University("Georgia", "Brewton-Parker College", 21696, 21696));
        universities.add(new University("Georgia", "Cambridge College of Healthcare & Technology - Atlanta", 14908, 14908));
        universities.add(new University("Georgia", "Central Georgia Technical College", 3082, 5482));
        universities.add(new University("Georgia", "Chamberlain University-Georgia", 20652, 20652));
        universities.add(new University("Georgia", "Chattahoochee Technical College", 3252, 5652));
        universities.add(new University("Georgia", "Clark Atlanta University", 24730, 24730));
        universities.add(new University("Georgia", "Clayton State University", 5068, 15790));
        universities.add(new University("Georgia", "Coastal Pines Technical College", 2759, 4906));
        universities.add(new University("Georgia", "College of Coastal Georgia", 3483, 10389));
        universities.add(new University("Georgia", "Columbia College - Fort Stewart", 8496, 8496));
        universities.add(new University("Georgia", "Columbia College - Hunter Army Airfield", 8496, 8496));
        universities.add(new University("Georgia", "Columbia College - NSB Kings Bay", 8496, 8496));
        universities.add(new University("Georgia", "Columbus State University", 5751, 16805));
        universities.add(new University("Georgia", "Columbus Technical College", 3042, 5442));
        universities.add(new University("Georgia", "Covenant College", 38860, 38860));
        universities.add(new University("Georgia", "Dalton Institute of Esthetics and Cosmetology", 14500, 14500));
        universities.add(new University("Georgia", "Dalton State College", 3283, 10189));
        universities.add(new University("Georgia", "DeVry University - Georgia", 15032, 15032));
        universities.add(new University("Georgia", "Digital Film Academy - Atlanta", 21150, 21150));
        universities.add(new University("Georgia", "East Georgia State College", 2736, 9088));
        universities.add(new University("Georgia", "East Georgia State College - Augusta", 3810, 10162));
        universities.add(new University("Georgia", "East Georgia State College - Statesboro", 4114, 10466));
        universities.add(new University("Georgia", "Elaine Sterling Institute", 17000, 17000));
        universities.add(new University("Georgia", "Emmanuel College", 22924, 22924));
        universities.add(new University("Georgia", "Emory University", 57948, 57948));
        universities.add(new University("Georgia", "Emory University - Oxford College", 57948, 57948));
        universities.add(new University("Georgia", "Empire Beauty School - Augusta", 19260, 19260));
        universities.add(new University("Georgia", "Empire Beauty School - Gwinnett", 19260, 19260));
        universities.add(new University("Georgia", "Empire Beauty School - Kennesaw", 19260, 19260));
        universities.add(new University("Georgia", "Empire Beauty School - Morrow", 19260, 19260));
        universities.add(new University("Georgia", "Empire Beauty School - Northlake", 19260, 19260));
        universities.add(new University("Georgia", "Empire Beauty School - Savannah", 19260, 19260));
        universities.add(new University("Georgia", "Fort Valley State University", 5832, 16554));
        universities.add(new University("Georgia", "Fortis College - Smyrna", 15515, 15515));
        universities.add(new University("Georgia", "Georgia Career Institute", 15400, 15400));
        universities.add(new University("Georgia", "Georgia College & State University", 8974, 28154));
        universities.add(new University("Georgia", "Georgia Gwinnett College", 4458, 13244));
        universities.add(new University("Georgia", "Georgia Highlands College", 2944, 9296));
        universities.add(new University("Georgia", "Georgia Institute of Cosmetology", 21895, 21895));
        universities.add(new University("Georgia", "Georgia Institute of Technology-Main Campus", 11764, 32876));
        universities.add(new University("Georgia", "Georgia Military College", 6705, 6705));
        universities.add(new University("Georgia", "Georgia Military College - Augusta", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Columbus", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Dublin", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Eastman", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Fairburn", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Fayetteville", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Madison", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Robins", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Sandersville", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Stone Mountain", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Valdosta", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Military College - Zebulon", 6638, 6638));
        universities.add(new University("Georgia", "Georgia Northwestern Technical College", 3112, 5512));
        universities.add(new University("Georgia", "Georgia Piedmont Technical College", 3158, 5558));
        universities.add(new University("Georgia", "Georgia Southern University", 5905, 16959));
        universities.add(new University("Georgia", "Georgia Southwestern State University", 4980, 15702));
        universities.add(new University("Georgia", "Georgia State University", 8478, 23709));
        universities.add(new University("Georgia", "Georgia State University-Perimeter College", 2960, 9312));
        universities.add(new University("Georgia", "Gordon State College", 3475, 10381));
        universities.add(new University("Georgia", "Grady Health System Professional Schools", 6940, 6940));
        universities.add(new University("Georgia", "Gupton Jones College of Funeral Service", 16935, 16935));
        universities.add(new University("Georgia", "Gwinnett College - Lilburn", 10500, 10500));
        universities.add(new University("Georgia", "Gwinnett College - Marietta Campus", 15390, 15390));
        universities.add(new University("Georgia", "Gwinnett College - Sandy Springs", 14000, 14000));
        universities.add(new University("Georgia", "Gwinnett Technical College", 3286, 5686));
        universities.add(new University("Georgia", "Helms College", 14117, 14117));
        universities.add(new University("Georgia", "Herzing University - Atlanta", 12750, 12750));
        universities.add(new University("Georgia", "Hogan Institute of Cosmetology and Esthetics", 13900, 13900));
        universities.add(new University("Georgia", "Institute of Medical Ultrasound", 28100, 28100));
        universities.add(new University("Georgia", "Interactive College of Technology - Chamblee", 11090, 11090));
        universities.add(new University("Georgia", "Interactive College of Technology - Gainesville", 10850, 10850));
        universities.add(new University("Georgia", "Interactive College of Technology - Morrow", 10850, 10850));
        universities.add(new University("Georgia", "International School of Skin Nailcare & Massage Therapy", 17350, 17350));
        universities.add(new University("Georgia", "Kennesaw State University", 5786, 17040));
        universities.add(new University("Georgia", "Keune Academy by 124", 19585, 19585));
        universities.add(new University("Georgia", "LaGrange College", 33700, 33700));
        universities.add(new University("Georgia", "Lanier Technical College", 3666, 6666));
        universities.add(new University("Georgia", "Life University", 14406, 14406));
        universities.add(new University("Georgia", "Lincoln College of Technology - Marietta", 29363, 29363));
        universities.add(new University("Georgia", "Luther Rice College & Seminary", 9808, 9808));
        universities.add(new University("Georgia", "MAK Beauty Institute", 15000, 15000));
        universities.add(new University("Georgia", "MAK Beauty Institute - Duluth", 15000, 15000));
        universities.add(new University("Georgia", "Mercer University", 30317, 30317));
        universities.add(new University("Georgia", "Miami Ad School - Atlanta", 19400, 19400));
        universities.add(new University("Georgia", "Middle Georgia State University", 3976, 12448));
        universities.add(new University("Georgia", "Miller-Motte College - Augusta", 20140, 20140));
        universities.add(new University("Georgia", "Miller-Motte College - Columbus", 21040, 21040));
        universities.add(new University("Georgia", "Miller-Motte College - Macon", 20140, 20140));
        universities.add(new University("Georgia", "Morehouse College", 29468, 29468));
        universities.add(new University("Georgia", "Morris Brown College", 9558, 9558));
        universities.add(new University("Georgia", "North Georgia Technical College", 3072, 5472));
        universities.add(new University("Georgia", "Oconee Fall Line Technical College", 3072, 5472));
        universities.add(new University("Georgia", "Ogeechee Technical College", 3140, 5540));
        universities.add(new University("Georgia", "Oglethorpe University", 43990, 43990));
        universities.add(new University("Georgia", "Paine College", 14596, 14596));
        universities.add(new University("Georgia", "Paul Mitchell the School - Atlanta", 18825, 18825));
        universities.add(new University("Georgia", "Paul Mitchell the School - Esani", 17800, 17800));
        universities.add(new University("Georgia", "Piedmont University", 29190, 29190));
        universities.add(new University("Georgia", "Point University", 22300, 22300));
        universities.add(new University("Georgia", "Pro Way Hair School", 21360, 21360));
        universities.add(new University("Georgia", "Profile Institute of Barber - Styling", 18650, 18650));
        universities.add(new University("Georgia", "Reformed University", 5360, 5360));
        universities.add(new University("Georgia", "Reinhardt University", 27300, 27300));
        universities.add(new University("Georgia", "Rivertown School of Beauty Barber Skin Care and Nails", 19400, 19400));
        universities.add(new University("Georgia", "Savannah College of Art and Design", 39605, 39605));
        universities.add(new University("Georgia", "Savannah State University", 5498, 16219));
        universities.add(new University("Georgia", "Savannah Technical College", 3042, 5442));
        universities.add(new University("Georgia", "Shorter University", 23258, 23258));
        universities.add(new University("Georgia", "South College-Atlanta", 17335, 17335));
        universities.add(new University("Georgia", "South Georgia State College", 2970, 9322));
        universities.add(new University("Georgia", "South Georgia Technical College", 3692, 6692));
        universities.add(new University("Georgia", "South University-Savannah", 16560, 16560));
        universities.add(new University("Georgia", "South University-Savannah Online", 16560, 16560));
        universities.add(new University("Georgia", "Southeastern Technical College", 3127, 5527));
        universities.add(new University("Georgia", "Southern Crescent Technical College", 3126, 5526));
        universities.add(new University("Georgia", "Southern Regional Technical College", 3002, 5402));
        universities.add(new University("Georgia", "Spelman College", 28885, 28885));
        universities.add(new University("Georgia", "Strayer University - Macon Campus", 13515, 13515));
        universities.add(new University("Georgia", "Strayer University-Augusta Campus", 13515, 13515));
        universities.add(new University("Georgia", "Strayer University-Cobb Campus", 13515, 13515));
        universities.add(new University("Georgia", "Strayer University-Columbus Campus", 13515, 13515));
        universities.add(new University("Georgia", "Strayer University-Georgia", 13515, 13515));
        universities.add(new University("Georgia", "Strayer University-Lithonia Campus", 13515, 13515));
        universities.add(new University("Georgia", "Strayer University-Morrow Campus", 13515, 13515));
        universities.add(new University("Georgia", "Strayer University-Savannah Campus", 13515, 13515));
        universities.add(new University("Georgia", "The Art Institute of Atlanta", 20794, 20794));
        universities.add(new University("Georgia", "Thomas University", 11080, 11080));
        universities.add(new University("Georgia", "Toccoa Falls College", 22350, 22350));
        universities.add(new University("Georgia", "Truett McConnell University", 24440, 24440));
        universities.add(new University("Georgia", "United Education Institute-Morrow", 19900, 19900));
        universities.add(new University("Georgia", "United Education Institute-Stone Mountain", 19900, 19900));
        universities.add(new University("Georgia", "University of Georgia", 11180, 30220));
        universities.add(new University("Georgia", "University of North Georgia", 5182, 15861));
        universities.add(new University("Georgia", "University of West Georgia", 5941, 16996));
        universities.add(new University("Georgia", "Valdosta State University", 6007, 17062));
        universities.add(new University("Georgia", "Webb's Barber School of Arts", 22500, 22500)); // Out-of-State fee not available
        universities.add(new University("Georgia", "Wesleyan College", 27650, 27650));
        universities.add(new University("Georgia", "West Georgia Technical College", 3122, 5522));
        universities.add(new University("Georgia", "Wiregrass Georgia Technical College", 3162, 5562));
        universities.add(new University("Georgia", "Woodruff Medical and Wellness Training", 11495, 11495)); // Only In-State fee available
        universities.add(new University("Georgia", "Young Harris College", 30905, 30905));
        universities.add(new University("Hawaii", "Brigham Young University - Hawaii", 6250, 6250));
        universities.add(new University("Hawaii", "Chaminade University of Honolulu", 28544, 28544));
        universities.add(new University("Hawaii", "Hawaii Pacific University", 31940, 31940));
        universities.add(new University("Hawaii", "Pacific Rim Christian University", 12380, 12380));
        universities.add(new University("Hawaii", "University of Hawaii at Hilo", 7838, 20798));
        universities.add(new University("Hawaii", "University of Hawaii at Manoa", 12186, 34218));
        universities.add(new University("Hawaii", "University of Hawaii Maui College", 3284, 8420));
        universities.add(new University("Hawaii", "University of Hawaii - West Oahu", 7584, 20544));
        universities.add(new University("Idaho", "Boise Bible College", 9770, 9770));
        universities.add(new University("Idaho", "Boise State University", 8364, 25701));
        universities.add(new University("Idaho", "Brigham Young University - Idaho", 4536, 4536));
        universities.add(new University("Idaho", "College of Southern Idaho", 4560, 6840));
        universities.add(new University("Idaho", "Idaho State University", 7958, 25936));
        universities.add(new University("Idaho", "Lewis-Clark State College", 6999, 20252));
        universities.add(new University("Idaho", "New Saint Andrews College", 14500, 14500));
        universities.add(new University("Idaho", "Northwest Nazarene University", 36298, 36298));
        universities.add(new University("Idaho", "The College of Idaho", 34630, 34630));
        universities.add(new University("Idaho", "University of Idaho", 8396, 27632));
        //Illinois
        //Indiana
        universities.add(new University("Iowa", "Allen College", 20008, 20008));
        universities.add(new University("Iowa", "Briar Cliff University", 34498, 34498));
        universities.add(new University("Iowa", "Buena Vista University", 38644, 38644));
        universities.add(new University("Iowa", "Central College", 19800, 19800));
        universities.add(new University("Iowa", "Clarke University", 38060, 38060));
        universities.add(new University("Iowa", "Coe College", 50664, 50664));
        universities.add(new University("Iowa", "Cornell College", 49158, 49158));
        universities.add(new University("Iowa", "Divine Word College", 14620, 14620));
        universities.add(new University("Iowa", "Dordt University", 34600, 34600));
        universities.add(new University("Iowa", "Drake University", 47742, 47742));
        universities.add(new University("Iowa", "Emmaus Bible College", 19800, 19800));
        universities.add(new University("Iowa", "Faith Baptist Bible College and Theological Seminary", 18740, 18740));
        universities.add(new University("Iowa", "Graceland University - Lamoni", 31970, 31970));
        universities.add(new University("Iowa", "Grand View University", 32068, 32068));
        universities.add(new University("Iowa", "Grinnell College", 61480, 61480));
        universities.add(new University("Iowa", "Iowa State University", 10133, 26617));
        universities.add(new University("Iowa", "Iowa Wesleyan University", 34700, 34700));
        universities.add(new University("Iowa", "Loras College", 36570, 36570));
        universities.add(new University("Iowa", "Luther College", 48160, 48160));
        universities.add(new University("Iowa", "Maharishi International University", 16530, 16530));
        universities.add(new University("Iowa", "Mercy College of Health Sciences", 16632, 16632));
        universities.add(new University("Iowa", "Morningside University", 36610, 36610));
        universities.add(new University("Iowa", "Mount Mercy University", 37606, 37606));
        universities.add(new University("Iowa", "Northwestern College", 34250, 34250));
        universities.add(new University("Iowa", "Palmer College of Chiropractic", 11025, 11025));
        universities.add(new University("Iowa", "Saint Ambrose University", 34570, 34570));
        universities.add(new University("Iowa", "Simpson College", 45108, 45108));
        universities.add(new University("Iowa", "St Luke's College", 20940, 20940));
        universities.add(new University("Iowa", "University of Dubuque", 38526, 38526));
        universities.add(new University("Iowa", "University of Iowa", 10353, 32316));
        universities.add(new University("Iowa", "University of Northern Iowa", 9411, 20565));
        universities.add(new University("Iowa", "Upper Iowa University", 33639, 33639));
        universities.add(new University("Iowa", "Wartburg College", 49190, 49190));
        universities.add(new University("Iowa", "William Penn University", 27800, 27800));
        universities.add(new University("Kansas", "Allen County Community College", 3780, 3780));
        universities.add(new University("Kansas", "Baker University", 32220, 32220));
        universities.add(new University("Kansas", "Baker University School of Professional and Graduate Studies and Graduate School of Education", 11120, 11120));
        universities.add(new University("Kansas", "Barclay College", 24990, 24990));
        universities.add(new University("Kansas", "Barton County Community College", 3840, 4608));
        universities.add(new University("Kansas", "Bellus Academy", 14025, 14025));
        universities.add(new University("Kansas", "Benedictine College", 33720, 33720));
        universities.add(new University("Kansas", "Bethany College", 31305, 31305));
        universities.add(new University("Kansas", "Bethel College-North Newton", 32090, 32090));
        universities.add(new University("Kansas", "Butler Community College", 4210, 6010));
        universities.add(new University("Kansas", "Central Christian College of Kansas", 20650, 20650));
        universities.add(new University("Kansas", "Cleveland University-Kansas City", 14400, 14400));
        universities.add(new University("Kansas", "Cloud County Community College", 3390, 3570));
        universities.add(new University("Kansas", "Coffeyville Community College", 3040, 4608));
        universities.add(new University("Kansas", "Coffeyville Community College - Coffeyville Technical Campus", 3040, 4608));
        universities.add(new University("Kansas", "Coffeyville Community College - Columbus Technical Campus", 3040, 4608));
        universities.add(new University("Kansas", "Colby Community College", 4114, 5654));
        universities.add(new University("Kansas", "Cowley County Community College", 4200, 5700));
        universities.add(new University("Kansas", "Crave Beauty Academy", 17500, 17500));
        universities.add(new University("Kansas", "Dodge City Community College", 4530, 4890));
        universities.add(new University("Kansas", "Donnelly College", 10372, 10372));
        universities.add(new University("Kansas", "Emporia State University", 7001, 14918));
        universities.add(new University("Kansas", "Eric Fisher Academy", 16855, 16855));
        universities.add(new University("Kansas", "Flint Hills Technical College", 6932, 6932));
        universities.add(new University("Kansas", "Fort Hays State University", 5430, 15870));
        universities.add(new University("Kansas", "Fort Scott Community College", 3600, 3600));
        universities.add(new University("Kansas", "Friends University", 31812, 31812));
        universities.add(new University("Kansas", "Garden City Community College", 3540, 4110));
        universities.add(new University("Kansas", "Haskell Indian Nations University", 480, 480));
        universities.add(new University("Kansas", "Hays Academy of Hair Design", 15100, 15100));
        universities.add(new University("Kansas", "Hays Academy of Hair Design, Salina", 15100, 15100));
        universities.add(new University("Kansas", "Hesston College", 29952, 29952));
        universities.add(new University("Kansas", "Highland Community College", 3330, 3330));
        universities.add(new University("Kansas", "Hutchinson Community College", 3600, 4530));
        universities.add(new University("Kansas", "Independence Community College", 4440, 4650));
        universities.add(new University("Kansas", "Johnson County Community College", 2784, 5472));
        universities.add(new University("Kansas", "Kansas Christian College", 9570, 9570));
        universities.add(new University("Kansas", "Kansas City Kansas Community College", 3164, 6244));
        universities.add(new University("Kansas", "Kansas State University", 10448, 26519));
        universities.add(new University("Kansas", "Kansas Wesleyan University", 32470, 32470));
        universities.add(new University("Kansas", "Labette Community College", 3968, 4768));
        universities.add(new University("Kansas", "Manhattan Area Technical College", 8400, 8400));
        universities.add(new University("Kansas", "Manhattan Christian College", 17914, 17914));
        universities.add(new University("Kansas", "McPherson College", 33536, 33536));
        universities.add(new University("Kansas", "MidAmerica Nazarene University", 34832, 34832));
        universities.add(new University("Kansas", "Midwest Barber College", 16335, 16335));
        universities.add(new University("Kansas", "Mitsu Sato Hair Academy", 11700, 11700));
        universities.add(new University("Kansas", "Neosho County Community College", 4416, 4416));
        universities.add(new University("Kansas", "Newman University", 34400, 34400));
        universities.add(new University("Kansas", "North Central Kansas Technical College", 8492, 8492));
        universities.add(new University("Kansas", "Northwest Kansas Technical College", 17100, 17100));
        universities.add(new University("Kansas", "Old Town Barber College-Wichita", 15850, 15850));
        universities.add(new University("Kansas", "Ottawa University-Kansas City", 12622, 12622));
        universities.add(new University("Kansas", "Ottawa University-Online", 12676, 12676));
        universities.add(new University("Kansas", "Ottawa University-Ottawa", 33380, 33380));
        universities.add(new University("Kansas", "Paul Mitchell the School-Overland Park", 17650, 17650));
        universities.add(new University("Kansas", "Paul Mitchell the School-Wichita", 16475, 16475));
        universities.add(new University("Kansas", "Pittsburg State University", 7774, 19118));
        universities.add(new University("Kansas", "Pratt Community College", 4036, 4552));
        universities.add(new University("Kansas", "Rasmussen University - Overland Park", 10571, 10571));
        universities.add(new University("Kansas", "Rasmussen University-Kansas", 13958, 13958));
        universities.add(new University("Kansas", "Salina Area Technical College", 7320, 7320));
        universities.add(new University("Kansas", "Seward County Community College", 3744, 4928));
        universities.add(new University("Kansas", "Southwestern College", 36650, 36650));
        universities.add(new University("Kansas", "Sterling College", 30000, 30000));
        universities.add(new University("Kansas", "Tabor College", 35050, 35050));
        universities.add(new University("Kansas", "University of Kansas", 11167, 28035));
        universities.add(new University("Kansas", "University of Saint Mary", 32540, 32540));
        universities.add(new University("Kansas", "Washburn Institute of Technology", 8640, 8640));
        universities.add(new University("Kansas", "Washburn University", 9126, 20130));
        universities.add(new University("Kansas", "WellSpring School of Allied Health-Lawrence", 16500, 16500));
        universities.add(new University("Kansas", "WellSpring School of Allied Health-Wichita", 15000, 15000));
        universities.add(new University("Kansas", "Wichita State University", 8866, 18226));
        universities.add(new University("Kansas", "Wichita State University-Campus of Applied Sciences and Technology", 5715, 6578));
        universities.add(new University("Kansas", "Wichita Technical Institute", 18085, 18085));
        universities.add(new University("Kansas", "Z Hair Academy", 17250, 17250));
        universities.add(new University("Kentucky", "Alice Lloyd College", 14250, 14250));
        universities.add(new University("Kentucky", "Asbury University", 33146, 33146));
        universities.add(new University("Kentucky", "Bellarmine University", 46030, 46030));
        universities.add(new University("Kentucky", "Berea College", 45026, 45026));
        universities.add(new University("Kentucky", "Brescia University", 27950, 27950));
        universities.add(new University("Kentucky", "Campbellsville University", 26100, 26100));
        universities.add(new University("Kentucky", "Centre College", 48070, 48070));
        universities.add(new University("Kentucky", "Clear Creek Baptist Bible College", 9970, 9970));
        universities.add(new University("Kentucky", "Eastern Kentucky University", 9844, 20222));
        universities.add(new University("Kentucky", "Georgetown College", 41600, 41600));
        universities.add(new University("Kentucky", "Kentucky Christian University", 23700, 23700));
        universities.add(new University("Kentucky", "Kentucky Mountain Bible College", 10060, 10060));
        universities.add(new University("Kentucky", "Kentucky State University", 9004, 12882));
        universities.add(new University("Kentucky", "Kentucky Wesleyan College", 31300, 31300));
        universities.add(new University("Kentucky", "Lindsey Wilson College", 26228, 26228));
        universities.add(new University("Kentucky", "Midway University", 25050, 25050));
        universities.add(new University("Kentucky", "Morehead State University", 9560, 14286));
        universities.add(new University("Kentucky", "Murray State University", 9432, 18888));
        universities.add(new University("Kentucky", "Northern Kentucky University", 10592, 20848));
        universities.add(new University("Kentucky", "Simmons College of Kentucky", 16398, 16398));
        universities.add(new University("Kentucky", "Spalding University", 27300, 27300));
        universities.add(new University("Kentucky", "The Southern Baptist Theological Seminary", 12000, 12000));
        universities.add(new University("Kentucky", "Thomas More University", 35810, 35810));
        universities.add(new University("Kentucky", "Transylvania University", 43670, 43670));
        universities.add(new University("Kentucky", "Union College", 30946, 30946));
        universities.add(new University("Kentucky", "University of Kentucky", 12859, 32276));
        universities.add(new University("Kentucky", "University of Louisville", 12520, 28866));
        universities.add(new University("Kentucky", "University of Pikeville", 23150, 23150));
        universities.add(new University("Kentucky", "University of the Cumberlands", 9875, 9875));
        universities.add(new University("Kentucky", "Western Kentucky University", 11112, 27000));
        universities.add(new University("Louisiana", "Bridges Christian College", 6600, 6600));
        universities.add(new University("Louisiana", "Centenary College of Louisiana", 38820, 38820));
        universities.add(new University("Louisiana", "Dillard University", 20224, 20224));
        universities.add(new University("Louisiana", "Franciscan Missionaries of Our Lady University", 15012, 15012));
        universities.add(new University("Louisiana", "Grambling State University", 7683, 16706));
        universities.add(new University("Louisiana", "Herzing University - New Orleans", 12750, 12750));
        universities.add(new University("Louisiana", "Louisiana Christian University", 19720, 19720));
        universities.add(new University("Louisiana", "Louisiana State University and Agricultural & Mechanical College", 11954, 28631));
        universities.add(new University("Louisiana", "Louisiana State University Health Sciences Center-New Orleans", 7020, 15495));
        universities.add(new University("Louisiana", "Louisiana State University Health Sciences Center-Shreveport", 8992, 19863));
        universities.add(new University("Louisiana", "Louisiana State University - Alexandria", 7050, 14650));
        universities.add(new University("Louisiana", "Louisiana State University - Shreveport", 7327, 20481));
        universities.add(new University("Louisiana", "Louisiana Tech University", 10065, 16806));
        universities.add(new University("Louisiana", "Loyola University New Orleans", 45030, 45030));
        universities.add(new University("Louisiana", "McNeese State University", 8440, 9940));
        universities.add(new University("Louisiana", "NationsUniversity", 1800, 1800));
        universities.add(new University("Louisiana", "New Orleans Baptist Theological Seminary", 10820, 10820));
        universities.add(new University("Louisiana", "Nicholls State University", 8156, 9249));
        universities.add(new University("Louisiana", "Northwestern State University of Louisiana", 8672, 19460));
        universities.add(new University("Louisiana", "Remington College - Shreveport Campus", 23477, 23477));
        universities.add(new University("Louisiana", "Saint Joseph Seminary College", 24725, 24725));
        universities.add(new University("Louisiana", "Southeastern Louisiana University", 8373, 20851));
        universities.add(new University("Louisiana", "Southern University and A & M College", 9848, 17198));
        universities.add(new University("Louisiana", "Southern University at New Orleans", 7471, 16371));
        universities.add(new University("Louisiana", "Tulane University of Louisiana", 62844, 62844));
        universities.add(new University("Louisiana", "University of Holy Cross", 15960, 15960));
        universities.add(new University("Louisiana", "University of Louisiana at Lafayette", 10382, 24110));
        universities.add(new University("Louisiana", "University of Louisiana at Monroe", 9082, 21182));
        universities.add(new University("Louisiana", "University of New Orleans", 9172, 14008));
        universities.add(new University("Louisiana", "Xavier University of Louisiana", 26863, 26863));
    }
}

